### PR TITLE
New_York_Times_Website_Clone

### PR DESCRIPTION
**Pull request by ntzwilly**
Setup repo

### CODE REVIEW

**Comment by ntzwilly** [comment]
Project 1: New York Times Website clone

**Review by SpaYco — CHANGES_REQUESTED** [review]
## Invalid 🛑 

in order to validate this project:

* [x] The project has a descriptive README.md ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_readme.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))
* [x] Pull Request has a meaningful title and a brief description ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_prs.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))

Best, 
Aziz Mejri 
_contact me on [twitter](https://twitter.com/iSpaYco) or slack (@SpaYco) if you need any help_

**Review by andresporras3423 — CHANGES_REQUESTED** [review]
### Status: Changes Required :recycle:
**Hello  Willy Ntazama** 
Good job with your first submission for this project :muscle:  :muscle:
There are some improvements to do before you can go ahead:

- [x] Your README file should include a link to the live demo
- [x] Your README file should include a screenshot of the live demo
- [x] Your README file must contains the authors names and social network (twitter, github, linkedin)
- [x] Your README file should contain the tools you used and how to set it up in the local environment.
- [x] In your project, the social Media Link should be aligned horizontally:
 
| Yours | Original |
|:---:|:---:|
|image | image |

- [x] The footer is incomplete

| Yours | Original |
|:---:|:---:|
|image | image |

- [x] Your page doesn't have the Editor's picks section
- [x] You should align elements with a combination of all three techniques (float, flex and grid)
 
Please request another review once you are ready! :+1: 
 
Happy coding :relaxed:
 
Oscar Andrés Russi Porras

**Comment by ntzwilly** [comment]
Project1:Make a clone of the New York Times Website

**Review by Temmarie — CHANGES_REQUESTED** [review]
## Changes Required! :recycle:

### Hi @ntzwilly  ! :wave: :wave:

#### You have done well so far :clap: However, there are changes required for you to make in order for this project to be approved. Kindly work on them and submit them for another code review.


**Recommended**

- [x] The social media row at the top of the page should be aligned with the main title.

**Main Content**
- [x] The background image should be aligned with the text. Adjust the size of this section to be as similar as possible to the actual site's.

- [x] The social media row in the comments section, just before the footer should be fixed.
- [x] Your page is still missing the editor's picks section.

**Optional**
- [x] For future references, use [font awesome](https://fontawesome.com/v4.7.0/icons/) for the icons on the page, especially the footer.
- [x] Use [this](https://chrome.google.com/webstore/detail/font-picker/mmjbimgpcbaegjiieojddickpjbdkeej) chrome extension to determine the font family and sizes used in the actual site.
- [x] Use [this](https://chrome.google.com/webstore/detail/svg-export/naeaaedieihlkmdajjefioajbbdbdjgp?hl=en-GB) SVG picker for SVG images for future reference.


__Kindly make the necessary changes and submit another code review request.__
_Feel free to reach me on slack for any inquiries about this review._ :wink:
__Grace Tamara Ekunola __
[GitHub](https://github.com/temmarie) | [LinkedIn](https://www.linkedin.com/in/ekunola-grace/) | [Twitter](https://twitter.com/TemmarieW)

**Comment by ntzwilly** [comment]
HTML&CSS first project: New York Times article copy

The background image is now aligned with the text. 
The social media row in the comments section, just before the footer is now fixed.
Editor's picks section added.

**Review by kobiyoyo — CHANGES_REQUESTED** [review]
## Hi Team    
#### Great Job so far, everything works fine, but there are a few more things required. 
### General 

- [x]  Your page is missing Editor's picks section on the rightmost side.

### Make changes and submit another code review request.
*Happy coding* 
(Any questions Feel free to contact me on slack @kobiyoyo)

**Review by layzrd — CHANGES_REQUESTED** [review]
### Status: Require changes 🌳 ♲
Hi @ntzwilly, I am Abdulaziz Redi Ali, your TSE for this PR.  👏👏  I appreciate your hard work in replicating nytimes.com.   Kindly fix the following issues.

[REQUIRED]

1. - [x] The editor's pick section should appear before "The Theory of Inflation" aside from the main article.


| # | Your Copy | Original | 
| :---:| :---:         |     :---:      |
| 1 | Screen Shot 2021-01-17 at 12 56 44 PM | Screen Shot 2021-01-17 at 12 44 10 PM |

Once you fix the issues, kindly submit another code review. ♲

Happy coding 👨‍💻
[Abdulaziz Redi Ali](https://azizali.ml/) | [Contact me on Slack](https://microverse-students.slack.com/team/U011SD6JUH2)

**Comment by ntzwilly** [comment]
Editor's picks section on the rightmost side Added

**Review by descholar-ceo — CHANGES_REQUESTED** [review]
# Status: Changes Required :vertical_traffic_light: :warning: 
## Hello @ntzwilly  :handshake: :handshake: :handshake: 

:+1: This is good to make it this far, your clone looks like the original page and it is really nice, congratulations on the good work you have done so far.
:+1: I liked that you have tried to implemented the requested changes from the previous review, keep it up, and your project is really almost done.
#### :warning: However we need to make few changes to mark this project approved, don't feel discouraged because of being asked some changes more and more, that's beacuse this is a learning process, and we are here to help you to become an out-standing developer. See the requested change below :point_down: :point_down: :point_down: 
### Note: All of requested changes which are marked as [Required] are mandatory to be implemented in order to get this project approved, others which are marked as [Optional] are nice to have in your project to make it outstanding

# [Required Changes] :red_circle: 
- [x] Links to your social media profiles don't work => Fix them
- [x] Add this pull request description => Talk about what you have worked on this pull request by answering questions like: What does this Pull Request do? and Which tasks to be completed on this Pull Request?
- [x] While working on your readme file, you have to follow the [microverse's readme template](https://github.com/microverseinc/readme-template)

# Optional Changes :yellow_circle: 
- [ ] It would be very nice if you write your links from the readme file using the link format of markdown language, example `[descholar-ceo](https://www.github.com/descholar-ceo)` => will produce [descholar-ceo](https://www.github.com/descholar-ceo)
___
_If anything seems to be unclear to you, reachout and ask anything by commenting on this Pull Request and mention me as [descholar-ceo](https://github.com/descholar-ceo), I will receive a notification and will respond._

[GitHub](https://github.com/descholar-ceo) | [LinkedIn](https://linkedin.com/in/mugirase-emmanuel) | [Twitter](https://twitter.com/descholar3)

_Reviewed by [Mugirase Emmanuel (descholar)](https://github.com/descholar-ceo)_

**Comment by ntzwilly** [comment]
Pull request Description:
- Fixing the social media links in the README.md file is done.
- Creating a read me file using the Microverse's readme template.

**Review by MuriloRoque — APPROVED** [review]
## Status: Approved :green_circle: 

### Hello @ntzwilly :wave: 

### Thank you for making all of the requested changes. Your project is approved :clap: :clap: :clap: 

### You may merge, good luck with your next projects :rocket: 

Murilo Roque Paiva da Silva

- Github: [@muriloroque](https://github.com/MuriloRoque)
- Linkedin: [MuriloRoque](https://www.linkedin.com/in/murilo-roque-b1268741/)

[Twitter Follow](https://twitter.com/MuriloRoquePai1)

**Pull request merged**
